---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:1.0.0
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysqlvolume
          mountPath: /var/lib/mysql
        envFrom:
        - configMapRef:
            name: mysql

  # this is PVC directly.
  volumeClaimTemplates:
  - metadata:
      name: mysqlvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs-dynamic-sc"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None #headless
  selector:
    app: mysql
    tier: db
    project: roboshop # has to match .spec.selector.matchLabel
  ports:
  - name: mysql-service-port
    protocol: TCP
    port: 3306 # this port belongs to service
    targetPort: mysql-port # this port belongs to container

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"
